config/routes.rb
HoursWorked::Application.routes.draw do
  
  get "pages/start"

  get "ajax/show"

  get "ajax/time"

  devise_for :users, :controllers => { :registrations => "registrations" }
  resources :users
  get "pages/index"
  get "pages/stop"
  get "pages/report"
  root to: 'pages#index'
  get '/pages/time', :to => 'pages#time'
  get '/time', :to => 'pages#time'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :start_at, :end_at, :hours_worked
  # attr_accessible :title, :body

  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    if user_signed_in?
      if (current_user.start_at == nil)
        redirect_to action: "start"
      else
        if (current_user.end_at == nil) 
  	      redirect_to action: "stop"
  	    else
  	      redirect_to action: "report"
  	    end
  	  end
  	end  
  end


  def start
  end

  def report
  	# if user_signed_in?
  	#   @xhours = current_user.updated_at - current_user.start_at
  	#   @growing_hours = current_user.hours_worked + xhours
  	# end  
  end

  def stop
  end

  def time
    respond_to do |format|
#      format.html { redirect_to "index" }
      format.js
    end
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  prepend_before_filter :require_no_authentication, :only => [ :new, :create, :cancel ]
  prepend_before_filter :authenticate_scope!, :only => [:edit, :update, :destroy]

   def update
    @user = User.find(current_user.id)
    email_changed = @user.email != params[:user][:email]
    password_changed = !params[:user][:password].empty?

    successfully_updated = if email_changed or password_changed
      @user.update_with_password(params[:user])
    else
      @user.update_without_password(params[:user])
    end

    if successfully_updated
      # Sign in the user bypassing validation in case his password changed
      sign_in @user, :bypass => true
      redirect_to root_path
    else
      render "edit"
    end
  end


  # GET /resource/sign_up
  def new
    resource = build_resource({})
    respond_with resource
  end

  # POST /resource
  def create
    build_resource

    if resource.save
      if resource.active_for_authentication?
        set_flash_message :notice, :signed_up if is_navigational_format?
        sign_in(resource_name, resource)
        respond_with resource, :location => after_sign_up_path_for(resource)
      else
        set_flash_message :notice, :"signed_up_but_#{resource.inactive_message}" if is_navigational_format?
        expire_session_data_after_sign_in!
        respond_with resource, :location => after_inactive_sign_up_path_for(resource)
      end
    else
      clean_up_passwords resource
      respond_with resource
    end
  end

  # GET /resource/edit
  def edit
    render :edit
  end

  # DELETE /resource
  def destroy
    resource.destroy
    Devise.sign_out_all_scopes ? sign_out : sign_out(resource_name)
    set_flash_message :notice, :destroyed if is_navigational_format?
    respond_with_navigational(resource){ redirect_to after_sign_out_path_for(resource_name) }
  end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  def cancel
    expire_session_data_after_sign_in!
    redirect_to new_registration_path(resource_name)
  end

  protected

  # Build a devise resource passing in the session. Useful to move
  # temporary session data to the newly created user.
  def build_resource(hash=nil)
    hash ||= resource_params || {}
    self.resource = resource_class.new_with_session(hash, session)
  end

  # The path used after sign up. You need to overwrite this method
  # in your own RegistrationsController.
  def after_sign_up_path_for(resource)
    after_sign_in_path_for(resource)
  end

  # The path used after sign up for inactive accounts. You need to overwrite
  # this method in your own RegistrationsController.
  def after_inactive_sign_up_path_for(resource)
    respond_to?(:root_path) ? root_path : "/"
  end

  # The default url to be used after updating a resource. You need to overwrite
  # this method in your own RegistrationsController.
  def after_update_path_for(resource)
    signed_in_root_path(resource)
  end

  # Authenticates the current scope and gets the current resource from the session.
  def authenticate_scope!
    send(:"authenticate_#{resource_name}!", :force => true)
    self.resource = send(:"current_#{resource_name}")
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end

   	 

end

app/helpers/registrations_helper.rb
module RegistrationsHelper
  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/views/layouts/_ajax.html.erb
<%= javascript_tag do -%>
$(document).ready(
  function(){
    setInterval(function(){
      $.ajax({
        url: "<%= 'time' %>",
        type: "GET",
        dataType: "script"
    });
  }, 1000 );
});
<% end -%>



<div id ='time_div'>The current time is <%= Time.zone.now %>
</div><br>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HoursWorked</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<% if user_signed_in? %>
  Logged in as <strong><%= current_user.email %></strong>.
  <%= link_to 'Edit profile', edit_user_registration_path %> |
  <%= link_to "Logout", destroy_user_session_path, method: :delete %>
<% else %>
  <%= link_to "Sign up", new_user_registration_path %> |
  <%= link_to "Login", new_user_session_path %>
<% end %>
<body>
<br><br>  
<%= render 'layouts/ajax' %> 

<h1>Hours worked</h1>

<%= yield %>

</body>
</html>

app/views/pages/report.html.erb
    <% if current_user.updated_at != nil %> 
      <% if current_user.start_at != nil %>
        <% xhours = current_user.updated_at.to_i - current_user.start_at.to_i %>
      <% end %>  
    <% end %>
    <% if current_user.hours_worked == nil %>
      <% current_user.hours_worked = 0 %>
    <% end %>
    <% growing_hours = current_user.hours_worked + xhours %>
    
    <p>Last session end at: <%= current_user.updated_at %></p>
    <% a = xhours %> 
      <p>Last session time worked: <%= a / 3600 %> hours <%= (a / 60).round - ((a / 3600).round * 60 ) %> minutes</p>
    <% b = growing_hours %> 
      <p>Hours_worked : <%= b / 3600 %> hours <%= (b / 60).round - ((b / 3600).round * 60 ) %> minutes</p>

    <%= form_for(resource, :as => resource_name, :url => registration_path(resource_name), :html => { :method => :put }) do |f| %>
    <%= devise_error_messages! %>    
    <%= f.hidden_field :email, :value => current_user.email %>
    <%= f.hidden_field :password %></div>
    <%= f.hidden_field :start_at, :value => nil %>
    <%= f.hidden_field :end_at, :value => nil %>
    <%= f.hidden_field :hours_worked, :value => growing_hours %>
    <div><%= f.submit "OK" %></div>
    <% end %>

app/views/pages/start.html.erb
  <% if current_user.updated_at != nil %>
   	<p>Last session end at: <%= current_user.updated_at %></p>
   	<% end %>
   	<% if current_user.hours_worked != nil %>
    <% a = current_user.hours_worked %> 
      <p>Hours_worked <%= a / 3600 %> hours <%= (a / 60).round - ((a / 3600).round * 60 ) %> minutes</p>
    <% end %>
    <%= form_for(resource, :as => resource_name, :url => registration_path(resource_name), :html => { :method => :put }) do |f| %>
    <%= devise_error_messages! %>    
    <%= f.hidden_field :email, :value => current_user.email %>
    <%= f.hidden_field :password %>
    <%= f.hidden_field :start_at, :value => Time.zone.now %>
    <%= f.hidden_field :end_at, :value => nil %>
    <div><%= f.submit "Start work" %></div>
    <% end %>

app/views/pages/stop.html.erb
    <p>Getting Started at <%= current_user.start_at %></p>
    <%= form_for(resource, :as => resource_name, :url => registration_path(resource_name), :html => { :method => :put }) do |f| %>
    <%= devise_error_messages! %>    
    <%= f.hidden_field :email, :value => current_user.email %>
    <%= f.hidden_field :password %>
    <%= f.hidden_field :end_at, :value => Time.zone.now  %>
    <div><%= f.submit "Stop work" %></div> 
    <% end %>

app/views/pages/time.js.erb
$('#time_div').html('<%= j render :text => "The current time is #{Time.zone.now.to_s}"%>');